#!/usr/bin/env bash
#
# ImageCtl — התקנה מלאה על שרת דביאן: שרשרת האתחול, השרת והקונסולה.
#
# הרצה אחת, כמה שאלות, וזהו:
#   1. איזה כרטיס לוילן השרתים (קונסולה/SSH) — ברירת המחדל: לקוח DHCP
#      של המכללה (#1088); סטטי = בחירה, אותן שאלות כמו בקונסולה
#   2. איזה כרטיס להפצה — או "לא עכשיו" (ברירת המחדל במסירה, #1088):
#      המנהל בוחר אותו מהקונסולה (דף הרשת: כתובת → DHCP), וזה משלים
#      את מה שהמתקין היה כותב כאן
# המנהל כברירת מחדל הוא admin/admin עם החלפה כפויה בקונסולה (#1085).
# `--admin-user` / `--admin-pass` נשארים לדיבאג — ואז בלי כפייה.
#
#   sudo ./setup-boot-server.sh
#
# כל השאר בקונסולה: DHCP לכל כרטיס (לשונית הרשת, אפיון סעיף 24),
# בדיקות מצב (מסך הבריאות). הטרמינל נוגעים בו פעם אחת — כאן.
#
# ראו docs/server-install.md להסבר מלא.

set -euo pipefail

# ---------------------------------------------------------------------------
# ברירות מחדל (הדגלים כולם רשות — לאוטומציה ולדיבאג, לא לזרימה הרגילה)
# ---------------------------------------------------------------------------

SERVER_URL=""
IFACE=""
IFACE_FROM_FLAG=0
SERVERS_IF=""
SERVERS_IF_FROM_FLAG=0
# ‏#1088: כרטיס השרתים — לקוח DHCP (ברירת מחדל) או סטטי; ‏DNS מופרד בפסיקים.
SERVERS_MODE="dhcp"
SERVERS_ADDR=""
SERVERS_MASK="255.255.255.0"
SERVERS_GW=""
SERVERS_DNS=""
NO_FIREWALL=0
ADMIN_USER=""
ADMIN_PASS=""
# Storage Nodes (#655/#723): תפקיד ההתקנה. standalone (ברירת מחדל) או
# secondary. משני מחייב כתובת שרת ראשי. **תצורת שרת בלבד** — לא נכנס
# לשורת הפקודה של הקרנל (עיקרון 2). מועבר ל-server.main דרך היחידה.
STORAGE_ROLE="standalone"
PRIMARY_URL=""
# ‏#703 (tracer 5): כתובת כרטיס הניהול שעליה הקונסולה (8081, HTTPS) מאזינה.
# ‏#1088: ריק = כרטיס השרתים שנבחר, **לפי שם** (השרת עוקב אחרי הכתובת
# שה-DHCP נותן). התעודה נוצרת כאן בכל מקרה, לפני ההרמה.
CONSOLE_HOST=""
TFTP_ROOT="/srv/tftp"
HTTP_ROOT="/srv/imagectl/boot"
APP_DIR="/opt/imagectl"
DATA_DIR="/var/lib/imagectl"
IMAGES_DIR="/srv/imagectl/images"
# הריפו שונה שמו ל-ImageCtl-archive ב-09/2026 והפך לפרטי; השם הישן
# `NadavOked/ImageCtl` שייך היום לפרויקט אחר, ו-clone ממנו היה מתקין
# קוד זר על שרת האתחול בלי להתלונן. ‏clone מהארכיון דורש אישורים
# ונכשל בקול — וזה המצב הרצוי מבין השניים.
REPO_URL="https://github.com/NadavOked/ImageCtl-archive"
DRY_RUN=0
PORT=8080

# ---------------------------------------------------------------------------
# הקובץ הקבוע ל-GRUB
# ---------------------------------------------------------------------------
#
# מוטמע כאן כדי שהסקריפט יעבוד גם בלי הריפו. המקור האמיתי הוא
# boot/grub_menu.py:render_bootstrap(); הטסט
# tests/test_installer_matches_generator.py משווה בין השניים.

read -r -d '' GRUB_BOOTSTRAP <<'GRUBCFG' || true
# ImageCtl bootstrap - generated by boot/grub_menu.py:render_bootstrap().
# Lives on the TFTP root as grub/grub.cfg. Regenerate, do not hand-edit.

set pager=0
set timeout=0
set timeout_style=hidden

# efinet exists only on UEFI; the i386-pc netboot core (the cloning
# machines, #38) has its driver built in, and insmod-ing a module that
# does not exist prints an error on the boot screen.
if [ "$grub_platform" = "efi" ]; then insmod efinet; fi
insmod http
insmod tftp

function try_chain {
    unset espdev
    search --no-floppy --file --set=espdev "$1"
    if [ -n "$espdev" ]; then
        set root=$espdev
        if chainloader "$1"; then
            boot
        else
            if [ -z "$chain_refused" ]; then set chain_refused=$1; fi
        fi
    fi
}

function chain_local {
    insmod part_gpt
    insmod fat
    insmod chain
    insmod search_fs_file
    unset chain_refused

    for path in /EFI/Microsoft/Boot/bootmgfw.efi /EFI/ubuntu/shimx64.efi /EFI/ubuntu/grubx64.efi /EFI/debian/shimx64.efi /EFI/debian/grubx64.efi /EFI/fedora/shimx64.efi /EFI/fedora/grubx64.efi /EFI/centos/shimx64.efi /EFI/rocky/shimx64.efi /EFI/almalinux/shimx64.efi /EFI/opensuse/shim.efi /EFI/BOOT/bootx64.efi; do
        try_chain "$path"
    done

    echo ""
    if [ -n "$chain_refused" ]; then
        echo "A boot loader WAS found on the local disk:"
        echo "  $chain_refused"
        echo "but this menu was refused permission to start it (see the error above)."
        if [ "$shim_lock" = "y" ]; then
            echo "Why: Secure Boot is on. Every chainload from this menu is checked"
            echo "by shim, and shim did not accept this file's signature."
            echo "The disk and the operating system are most likely intact."
            echo "To start it now: power off, then boot from the disk directly"
            echo "(firmware boot menu, usually F12), bypassing PXE."
        else
            echo "Why: unknown. GRUB does not report a shim lock, so this is"
            echo "not a Secure Boot refusal. Read the error above."
        fi
    else
        echo "No operating system found on the local disk."
    fi
    echo "Contact IT. This computer will stay powered on."
    set stay_on=y
    while [ "$stay_on" = "y" ]; do
        sleep --interruptible 60
    done
}

function try_local {
    if [ "$grub_platform" = "efi" ]; then
        echo "Booting from the local disk."
        chain_local
    fi

    echo ""
    echo "This machine booted in Legacy BIOS mode, which on this network"
    echo "means a cloning machine. It has no local system to start, and the"
    echo "drives attached to it are the payload - they are never booted from."
    echo "Nothing will be started."
    echo "Fix the server or the network, then power-cycle this machine."
    echo "Contact IT. This computer will stay powered on."
    set stay_on=y
    while [ "$stay_on" = "y" ]; do
        sleep --interruptible 60
    done
}

# GRUB fills net_default_mac from the interface that PXE-booted, already in
# lowercase-with-colons form -- the canonical format from the interface spec.
if [ -z "$net_default_mac" ]; then
    echo "ImageCtl: no network interface reported."
    sleep --interruptible 3
    try_local
fi

# Deployment address. net_default_server -- the DHCP or PXE-proxy server that
# actually answered this station -- comes first, because it is the only address
# that is right on every network: a station booted by a proxy on a foreign VLAN
# (spec scenario 3) often cannot reach the deployment VLAN address at all. The
# port is not in DHCP, so it comes from the configured address.
# The explicit address stays as a fallback, for debugging and for the case
# where next-server arrives empty or points at a machine without ImageCtl.
set imagectl_fallback=@@GRUB_HOST@@
if [ -n "$net_default_server" ]; then
    set imagectl_server=${net_default_server}:@@GRUB_PORT@@
else
    set imagectl_server=$imagectl_fallback
fi

# Three attempts: GRUB's EFI http stack sometimes fails its very first
# connection on a cold boot while TFTP already works (#31). A retry a
# second later succeeds; only a server that is really down falls through.
# Each attempt also tries the fallback, unless it is the same address.
for attempt in 1 2 3; do
    configfile (http,$imagectl_server)/boot/menu?mac=$net_default_mac
    if [ "$imagectl_server" != "$imagectl_fallback" ]; then
        configfile (http,$imagectl_fallback)/boot/menu?mac=$net_default_mac
    fi
    sleep 1
done

# Reached only if every fetch failed -- server down, cable out, DHCP wrong.
# try_local, not chain_local: this file runs before the machine has asked
# about its own MAC, so it cannot know it is a cloning machine -- and with
# the server down there is nobody to ask. $grub_platform is the one thing
# it does know (#323).
echo "ImageCtl: server $imagectl_server unreachable."
sleep --interruptible 3
try_local
GRUBCFG

# ---------------------------------------------------------------------------
# עזרים
# ---------------------------------------------------------------------------

RED=$'\033[31m'; YEL=$'\033[33m'; GRN=$'\033[32m'; DIM=$'\033[2m'; OFF=$'\033[0m'

say()  { printf '%s==>%s %s\n' "$GRN" "$OFF" "$*"; }
warn() { printf '%s[!]%s %s\n' "$YEL" "$OFF" "$*" >&2; }
die()  { printf '%s[x]%s %s\n' "$RED" "$OFF" "$*" >&2; exit 1; }

run() {
    if (( DRY_RUN )); then
        printf '%s    would run: %s%s\n' "$DIM" "$*" "$OFF"
    else
        "$@"
    fi
}

write_file() {
    # write_file <path> <<'EOF' ... EOF
    local path="$1" content
    content="$(cat)"
    if (( DRY_RUN )); then
        printf '%s    would write %s (%d bytes)%s\n' "$DIM" "$path" "${#content}" "$OFF"
        return
    fi
    install -d "$(dirname "$path")"
    if [[ -f "$path" ]] && ! grep -q "ImageCtl" "$path" 2>/dev/null; then
        # קובץ שלא אנחנו כתבנו — מגבים במקום לדרוס.
        cp -a "$path" "${path}.pre-imagectl.$(date +%Y%m%d%H%M%S)"
        warn "backed up existing $path"
    fi
    printf '%s\n' "$content" > "$path"
}

usage() {
    cat <<'EOF'
ImageCtl — התקנה מלאה על שרת דביאן: שרשרת אתחול, שרת וקונסולה.

  sudo ./setup-boot-server.sh

ההתקנה שואלת על כרטיס וילן השרתים (לקוח DHCP של המכללה כברירת מחדל,
או סטטי — #1088), על כרטיס ההפצה (או "לא עכשיו" — המנהל יבחר אותו
מהקונסולה), ומרימה הכל — כולל חומת אש nftables לפי וילן (#1074). המנהל
הוא admin/admin עם החלפה כפויה בקונסולה (#1085); --admin-pass לדיבאג.
DHCP לא נדלק כאן בכלל — מגדירים אותו אחר כך מהקונסולה, לשונית הרשת,
עם כל שכבות הבטיחות (אפיון סעיף 24). בלי כרטיס הפצה dnsmasq אינו מופעל
ו-grub.cfg אינו נכתב — ההדלקה מהקונסולה משלימה את שניהם.

דגלים (רשות — לאוטומציה ולדיבאג בלבד):
  --deploy-if IFACE    כרטיס ההפצה (מדלג על השאלה); --interface הוא שם ישן לאותו דגל
  --servers-if IFACE   כרטיס וילן השרתים (קונסולה 8081, SSH); בלי דגל — נשאל, או = כרטיס ההפצה באוטומציה
  --servers-mode MODE  dhcp (ברירת מחדל) או static לכרטיס השרתים (#1088)
  --servers-address A  --servers-netmask M  --servers-gateway G  --servers-dns D1,D2
                       פרטי הכתובת הסטטית לכרטיס השרתים (עם --servers-mode static)
  --no-firewall        מדלג על nftables, עם אזהרה ביומן (R20-F1)
  --server-url URL     עוקף את הכתובת הנגזרת מהכרטיס (http בלבד)
  --admin-user NAME    מדלג על שאלת המשתמש
  --admin-pass PASS    מדלג על שאלות הסיסמה (נשאר בהיסטוריית השלל — לדיבאג)
  --tftp-root PATH     ברירת מחדל /srv/tftp
  --http-root PATH     ברירת מחדל /srv/imagectl/boot; מועבר לשרת כ---boot-dir
  --storage-role ROLE  standalone (ברירת מחדל) או secondary (#655/#723)
  --primary-url URL    כתובת השרת הראשי — חובה ל-secondary
  --console-host ADDR  כתובת/שם כרטיס הניהול לקונסולה (8081, HTTPS); ברירת מחדל: כרטיס השרתים לפי שם (#1088)
  --dry-run            מראה מה יקרה בלי לשנות כלום
  -h, --help           המסך הזה
EOF
}

# ---------------------------------------------------------------------------
# פירוק ארגומנטים
# ---------------------------------------------------------------------------

while [[ $# -gt 0 ]]; do
    case "$1" in
        --interface|--deploy-if) IFACE="${2:?}"; IFACE_FROM_FLAG=1; shift 2 ;;
        --servers-if)  SERVERS_IF="${2:?}"; SERVERS_IF_FROM_FLAG=1; shift 2 ;;
        --servers-mode) SERVERS_MODE="${2:?}"; shift 2 ;;
        --servers-address) SERVERS_ADDR="${2:?}"; shift 2 ;;
        --servers-netmask) SERVERS_MASK="${2:?}"; shift 2 ;;
        --servers-gateway) SERVERS_GW="${2:?}"; shift 2 ;;
        --servers-dns) SERVERS_DNS="${2:?}"; shift 2 ;;
        --no-firewall) NO_FIREWALL=1; shift ;;
        --server-url)  SERVER_URL="${2:?}"; shift 2 ;;
        --admin-user)  ADMIN_USER="${2:?}"; shift 2 ;;
        --admin-pass)  ADMIN_PASS="${2:?}"; shift 2 ;;
        --tftp-root)   TFTP_ROOT="${2:?}"; shift 2 ;;
        --http-root)   HTTP_ROOT="${2:?}"; shift 2 ;;
        --storage-role) STORAGE_ROLE="${2:?}"; shift 2 ;;
        --primary-url) PRIMARY_URL="${2:?}"; shift 2 ;;
        --console-host) CONSOLE_HOST="${2:?}"; shift 2 ;;
        --dry-run)     DRY_RUN=1; shift ;;
        -h|--help)     usage; exit 0 ;;
        --mode|--dhcp-range)
            die "הדגל $1 בוטל: DHCP מוגדר מהקונסולה, לשונית הרשת (אפיון סעיף 24)." ;;
        *)             die "unknown option: $1  (try --help)" ;;
    esac
done

(( DRY_RUN )) || [[ $EUID -eq 0 ]] || die "צריך להריץ עם sudo (או --dry-run כדי רק לראות)."

# ---------------------------------------------------------------------------
# שאלה 1 — כרטיס וילן השרתים (קונסולה 8081, SSH 22), מתוך רשימה של מה שקיים
# ---------------------------------------------------------------------------
#
# ‏#1088: הכרטיס הזה הוא לקוח DHCP של המכללה כברירת מחדל — הכתובת מגיעה
# מה-DHCP של רשת השרתים, ו-`hostname` (אופציה 12) נשלח כדי שה-DNS שם
# יפתור את שם השרת. הקונסולה נקשרת אליו **לפי שם** (--console-host <if>)
# ומאזינה מחדש כשהכתובת משתנה. סטטי הוא בחירה, באותן שאלות כמו בקונסולה.

iface_ip() { ip -4 -o addr show dev "$1" 2>/dev/null | awk '{print $4}' | cut -d/ -f1 | head -n1; }

list_nics() {
    mapfile -t NICS < <(ip -br link | awk '$1 != "lo" {print $1}' | cut -d@ -f1)
    (( ${#NICS[@]} )) || die "לא נמצאו כרטיסי רשת."
    for i in "${!NICS[@]}"; do
        n="${NICS[$i]}"
        state="$(cat "/sys/class/net/$n/operstate" 2>/dev/null || echo '?')"
        printf '  %d) %-12s %-6s %s\n' "$((i + 1))" "$n" "$state" "$(iface_ip "$n")"
    done
}

if [[ -z "$SERVERS_IF" ]]; then
    if (( IFACE_FROM_FLAG )); then
        # אוטומציה (--deploy-if בלי --servers-if): אותו כרטיס, כדי לא לשבור סקריפטים.
        SERVERS_IF="$IFACE"
    else
        say "כרטיס וילן השרתים (קונסולה HTTPS, SSH ניהול):"
        list_nics
        read -r -p "על איזה כרטיס וילן השרתים? [1]: " pick
        pick="${pick:-1}"
        [[ "$pick" =~ ^[0-9]+$ ]] && (( pick >= 1 && pick <= ${#NICS[@]} ))             || die "אין כרטיס מספר $pick ברשימה."
        SERVERS_IF="${NICS[$((pick - 1))]}"
        read -r -p "כתובת לכרטיס השרתים — DHCP מהמכללה (d) או סטטית (s)? [d]: " mode_pick
        case "${mode_pick:-d}" in
            d|D|dhcp)   SERVERS_MODE="dhcp" ;;
            s|S|static) SERVERS_MODE="static"
                        read -r -p "  כתובת: " SERVERS_ADDR
                        read -r -p "  מסכה [255.255.255.0]: " SERVERS_MASK
                        SERVERS_MASK="${SERVERS_MASK:-255.255.255.0}"
                        read -r -p "  שער (ריק = בלי): " SERVERS_GW
                        read -r -p "  DNS (מופרד בפסיקים, ריק = בלי): " SERVERS_DNS ;;
            *)          die "תשובה לא מוכרת: $mode_pick (d או s)" ;;
        esac
    fi
fi
ip link show "$SERVERS_IF" >/dev/null 2>&1 || die "לא קיים ממשק בשם $SERVERS_IF"
case "$SERVERS_MODE" in
    dhcp)   ;;
    static) [[ -n "$SERVERS_ADDR" ]] || die "כרטיס שרתים סטטי מחייב כתובת (--servers-address)" ;;
    *)      die "--servers-mode חייב להיות dhcp או static (התקבל: $SERVERS_MODE)" ;;
esac

# ---------------------------------------------------------------------------
# שאלה 2 — כרטיס ההפצה, או "לא עכשיו" (#1088)
# ---------------------------------------------------------------------------
#
# במסירה למכללה רשת ההפצה **אינה מוגדרת** כאן: המנהל בוחר את הכרטיס מדף
# הרשת בקונסולה, קובע לו כתובת סטטית ומדליק DHCP — וההדלקה משלימה כל מה
# שהמתקין היה כותב לכרטיס ההפצה (grub.cfg, dnsmasq באתחול, חומת אש,
# והכתובת ליחידה). בלי כרטיס הפצה: dnsmasq לא מופעל, grub.cfg לא נכתב,
# והשרת עולה במצב "רשת ההפצה לא הוגדרה" (הסוכן על loopback בלבד).

# באוטומציה (--servers-if בלי --deploy-if) אין שאלה: "לא עכשיו".
if [[ -z "$IFACE" && ! $SERVERS_IF_FROM_FLAG -eq 1 ]]; then
    say "כרטיס ההפצה (DHCP/TFTP/מולטיקאסט למחשבי השיכפול והבנייה):"
    printf '  0) לא עכשיו — המנהל יבחר אותו מהקונסולה (דף הרשת)\n'
    list_nics
    read -r -p "על איזה כרטיס תוגדר רשת ההפצה? [0]: " pick
    pick="${pick:-0}"
    if [[ "$pick" == "0" ]]; then
        IFACE=""
    else
        [[ "$pick" =~ ^[0-9]+$ ]] && (( pick >= 1 && pick <= ${#NICS[@]} ))             || die "אין כרטיס מספר $pick ברשימה."
        IFACE="${NICS[$((pick - 1))]}"
    fi
fi
if [[ -n "$IFACE" ]]; then
    ip link show "$IFACE" >/dev/null 2>&1 || die "לא קיים ממשק בשם $IFACE"
    # הכתובת נגזרת מהכרטיס — אין סיבה להקליד אותה.
    if [[ -z "$SERVER_URL" ]]; then
        ADDR="$(iface_ip "$IFACE")"
        [[ -n "$ADDR" ]] || die "לכרטיס $IFACE אין כתובת IP.
    קבעו לו כתובת סטטית (זה שרת) והריצו שוב — או בחרו 'לא עכשיו' והגדירו מהקונסולה."
        SERVER_URL="http://$ADDR:$PORT"
    fi
elif [[ -n "$SERVER_URL" ]]; then
    die "--server-url בלי כרטיס הפצה (--deploy-if) — הכתובת חייבת לשבת על כרטיס"
fi
# ‏#1088: ‏--console-host ברירת מחדל = כרטיס השרתים **לפי שם** — השרת פותר
# את הכתובת בעלייה ומאזין מחדש בהחלפתה. כתובת מפורשת (הדגל) גוברת.
CONSOLE_HOST="${CONSOLE_HOST:-$SERVERS_IF}"

case "$SERVER_URL" in
    "")        ;;   # #1088: אין כרטיס הפצה עדיין — הכתובת תיקבע מהקונסולה
    http://*)  ;;
    https://*) die "https לא נתמך: ה-GRUB החתום של דביאן נבנה בלי TLS. השתמש ב-http." ;;
    *)         die "--server-url חייב להתחיל ב-http:// (התקבל: $SERVER_URL)" ;;
esac
# תצורת ה-Storage Node (#655/#723): משני מחייב כתובת שרת ראשי לא-ריקה,
# ותצורה סותרת נכשלת בקול ולא מתגלגלת ל-standalone בשקט (עיקרון 5).
# standalone מתעלם מ---primary-url. השרת מאמת שוב (server.main) — כאן זה
# רק כדי לעצור מוקדם, לפני שמתקינים חצי שירות.
case "$STORAGE_ROLE" in
    standalone) PRIMARY_URL="" ;;
    secondary)  [[ -n "$PRIMARY_URL" ]] || die "שרת משני מחייב --primary-url" ;;
    *)          die "--storage-role חייב להיות standalone או secondary (התקבל: $STORAGE_ROLE)" ;;
esac

GRUB_HOST=""; GRUB_PORT=80
if [[ -n "$SERVER_URL" ]]; then
    GRUB_HOST="${SERVER_URL#http://}"; GRUB_HOST="${GRUB_HOST%%/*}"
    # הפורט לבדו — קובץ ה-GRUB מרכיב איתו את הכתובת שה-DHCP/proxy ענה בפועל.
    # ‏if מלא ולא "&&": תחת set -e תנאי שנכשל בשורה עליונה מפיל את הסקריפט.
    GRUB_PORT="${GRUB_HOST##*:}"
    if [[ "$GRUB_PORT" == "$GRUB_HOST" ]]; then GRUB_PORT=80; fi
fi

# ---------------------------------------------------------------------------
# שאלות 2–4 — משתמש המנהל
# ---------------------------------------------------------------------------

ADMIN_USER="${ADMIN_USER:-admin}"
# בלי --admin-pass: admin/admin, והקונסולה תדרוש החלפה. לא שואלים סיסמה.

say "כרטיס הפצה: ${IFACE:-לא עכשיו (מהקונסולה)} · כרטיס שרתים: $SERVERS_IF ($SERVERS_MODE) · כתובת הפצה: ${SERVER_URL:-תיקבע מהקונסולה} · מנהל: $ADMIN_USER"

# ---------------------------------------------------------------------------
# חבילות וקוד
# ---------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PKGS=(shim-signed grub-efi-amd64-signed grub-pc-bin dnsmasq
      python3-fastapi python3-uvicorn
      python3-websockets                      # #904: uvicorn WebSocket — בלעדיו המוניטור (#690) מחזיר 500
      python3-cryptography python3-openssl    # #740: mTLS enrollment בין-שרתי
      open-iscsi nfs-common cifs-utils)       # #1066: יוזם iSCSI + לקוח NFS/SMB
[[ -f "$SCRIPT_DIR/../server/main.py" ]] || PKGS+=(git)

say "מתקין חבילות: ${PKGS[*]}"
run env DEBIAN_FRONTEND=noninteractive apt-get update -qq
run env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq "${PKGS[@]}"

if [[ -f "$SCRIPT_DIR/../server/main.py" ]]; then
    SRC="$(cd "$SCRIPT_DIR/.." && pwd)"
    if [[ "$SRC" != "$APP_DIR" ]]; then
        say "מעתיק את הקוד אל $APP_DIR"
        run install -d "$APP_DIR"
        run cp -a "$SRC/." "$APP_DIR/"
    fi
else
    # ‏git נכשל כאן בקול, אבל בהודעה **שלו**: "could not read Username for
    # 'https://github.com'". למי שמתקין שרת ואינו מכיר את הריפו זו הודעה
    # שאינה אומרת לא מה קרה ולא מה לעשות — ‏ImageCtl-archive הוא ריפו
    # פרטי, ו-clone אנונימי ממנו לא יצליח לעולם. אותו דפוס כמו
    # ‏`Unable to locate package` של fonts-ibm-plex (#120): כשל אמיתי,
    # הודעה שמובילה לכיוון הלא נכון.
    say "מושך את הקוד מ-$REPO_URL"
    if [[ -d "$APP_DIR/.git" ]]; then
        run git -C "$APP_DIR" pull --ff-only || die "\
עדכון הקוד ב-$APP_DIR נכשל (git pull). ראה את שגיאת git למעלה."
    else
        run git clone --depth 1 "$REPO_URL" "$APP_DIR" || die "\
‏git clone מ-$REPO_URL נכשל.

‏ImageCtl-archive הוא ריפו **פרטי**: ‏clone בלי אישורים נכשל תמיד, וזו
הסיבה הסבירה ביותר לשגיאת git שמופיעה למעלה.

הדרך המומלצת — להביא את הריפו אל השרת ולהריץ את המתקין מתוכו:

  (מתחנה שיש לה גישה לריפו)
  git clone https://github.com/NadavOked/ImageCtl-archive imagectl
  tar czf imagectl.tgz imagectl && scp imagectl.tgz <שרת>:/tmp/

  (על השרת)
  tar xzf /tmp/imagectl.tgz -C ~ && cd ~/imagectl
  sudo bash install/setup-boot-server.sh

כשהריפו נמצא לצד הסקריפט המתקין מעתיק ממנו ואינו פונה לרשת כלל.
לחלופין: הגדר אישורי git על השרת (credential helper או SSH) והרץ שוב."
    fi
fi

# ---------------------------------------------------------------------------
# שרשרת האתחול: shim ו-GRUB חתומים + הקובץ הקבוע
# ---------------------------------------------------------------------------
#
# שני הקבצים חייבים להיות אלה של דביאן — shim חתום מיקרוסופט ו-GRUB
# חתום דביאן. shim מחפש את grubx64.efi בשם הזה בדיוק, באותה תיקייה.

SHIM_SRC="/usr/lib/shim/shimx64.efi.signed"
GRUB_SRC="/usr/lib/grub/x86_64-efi-signed/grubnetx64.efi.signed"

say "מעתיק shim ו-GRUB חתומים אל $TFTP_ROOT"
for src in "$SHIM_SRC" "$GRUB_SRC"; do
    [[ -f "$src" ]] || (( DRY_RUN )) || die "לא נמצא: $src — בדוק: dpkg -L shim-signed | grep efi"
done
run install -d -m 0755 "$TFTP_ROOT" "$TFTP_ROOT/grub" "$HTTP_ROOT" "$IMAGES_DIR" \
    "$DATA_DIR/storage"

# #1066: initiator name ייחודי לשרת הזה — hostname + machine-id.
# נכתב מחדש לאותו ערך בכל הרצת מתקין (יציב), כדי ש-ACL ב-NAS לא יזוז.
if (( ! DRY_RUN )); then
    run install -d -m 0755 /etc/iscsi
    host=$(hostname -s 2>/dev/null || echo imagectl)
    uuid=$(cat /etc/machine-id 2>/dev/null || cat /proc/sys/kernel/random/uuid)
    printf 'InitiatorName=iqn.2026-09.imagectl.%s:%s\n' "$host" "$uuid" \
        > /etc/iscsi/initiatorname.iscsi
    chmod 0644 /etc/iscsi/initiatorname.iscsi
fi
run install -m 0644 "$SHIM_SRC" "$TFTP_ROOT/bootx64.efi"
run install -m 0644 "$GRUB_SRC" "$TFTP_ROOT/grubx64.efi"

# מחשבי השיכפול הם Legacy BIOS (#38) — GRUB i386-pc לרשת, מאותו עץ
# grub/ ועם אותו grub.cfg בדיוק. ה-DHCP בוחר טוען לפי אופציה 93.
say "בונה GRUB i386-pc למחשבי ה-Legacy (grub-mknetdir)"
run grub-mknetdir --net-directory="$TFTP_ROOT" --subdir=grub

if [[ -z "$IFACE" ]]; then
    # ‏#1088: כתובת הנפילה ב-grub.cfg היא כתובת ההפצה — אין עדיין. הקונסולה
    # כותבת את הקובץ (server/deploy_net.py, אותו מחולל) בהדלקת DHCP.
    say "grub/grub.cfg לא נכתב — ייכתב מהקונסולה כשתוגדר רשת ההפצה"
else
    say "כותב את grub/grub.cfg עבור $GRUB_HOST"
    CFG_TEXT="${GRUB_BOOTSTRAP//@@GRUB_HOST@@/$GRUB_HOST}"
    CFG_TEXT="${CFG_TEXT//@@GRUB_PORT@@/$GRUB_PORT}"
    if (( DRY_RUN )); then
        printf '%s    would write %s/grub/grub.cfg%s\n' "$DIM" "$TFTP_ROOT" "$OFF"
    else
        printf '%s\n' "$CFG_TEXT" > "$TFTP_ROOT/grub/grub.cfg"
        chmod 0644 "$TFTP_ROOT/grub/grub.cfg"
    fi
fi

# אין tftp-secure, בכוונה: הוא מגיש רק קבצים שבבעלות משתמש dnsmasq,
# ובשרת אתחול ייעודי שכל תוכנו ציבורי ממילא הוא לא מגן על כלום — רק
# מוסיף כשל שקט ("Permission denied") לכל קובץ חדש שנכתב כ-root.
# נכווינו פעמיים (#12, #38). ‏tftp-root תוחם את ההגשה לתיקייה הזו.

# ---------------------------------------------------------------------------
# dnsmasq — TFTP בלבד. DHCP לא נדלק בהתקנה: הוא מוגדר מהקונסולה,
# כרטיס-כרטיס, מאחורי שכבות הבטיחות של סעיף 24. הקונסולה כותבת
# ל-imagectl-dhcp.conf; הקובץ הזה נותן את הבסיס המשותף בלבד.
# ---------------------------------------------------------------------------

say "מגדיר dnsmasq (TFTP בלבד; DHCP יוגדר מהקונסולה)"
# ‏#1088: בלי כרטיס הפצה אין `interface=` לכתוב — השורה שמצמידה את ה-TFTP
# לכרטיס ההפצה בלבד (R20-F1) נכתבת אז מהקונסולה ב-imagectl-dhcp.conf
# (‏dhcp.render עם deploy_interface), ו-dnsmasq **אינו** מופעל כאן: בלי
# ‏interface= ועם bind-interfaces הוא היה מאזין ל-69 על כל הכרטיסים.
if [[ -n "$IFACE" ]]; then
    DNSMASQ_IFACE_LINES="interface=$IFACE
bind-interfaces"
else
    DNSMASQ_IFACE_LINES="# interface= is written by the console (imagectl-dhcp.conf) once the
# deploy NIC is chosen there (#1088). Until then dnsmasq stays disabled."
fi
# #141: dhcp-hostsfile למטה מצביע על קובץ הזה — אם הוא לא קיים, dnsmasq
# מסרב לעלות (וה-restart שאחרי ה-heredoc נכשל, לפני שהשרת עצמו רץ אפילו
# פעם אחת ויכול לכתוב אותו). placeholder ריק זהה למה שהשרת כותב בעצמו
# כשאין אף מכונה רשומה (dhcp.render_known_macs([])) — הוא נדרס בפעם
# הראשונה שהשרת עולה או שמכונה נוספת מהקונסולה.
write_file /etc/imagectl/known-macs <<'EOF'
# ImageCtl -- registered MAC addresses, generated from the console (#141).
# Do not edit by hand: the next machine add/edit/delete rewrites it.
EOF
write_file /etc/dnsmasq.d/imagectl.conf <<EOF
# ImageCtl — נוצר על ידי install/setup-boot-server.sh. אל תערוך ביד.
# DHCP מוגדר מהקונסולה (לשונית הרשת) ונכתב ל-imagectl-dhcp.conf.
port=0

# ‏#1074 / R20-F1: TFTP רק על כרטיס ההפצה. בלי interface= + bind-interfaces
# dnsmasq מאזין ל-69 על כל הכרטיסים מההתקנה. הקונסולה תוסיף interface=
# נוספים ב-imagectl-dhcp.conf אם יודלק DHCP על כרטיס אחר.
$DNSMASQ_IFACE_LINES

enable-tftp
tftp-root=$TFTP_ROOT
# אין צורך לקבוע גודל בלוק: ‏dnsmasq נענה אוטומטית ל-blksize שהלקוח
# מבקש (קושחות PXE מבקשות ~1468). ‏tftp-blocksize אינה אופציה קיימת —
# השירות מסרב לעלות איתה; ‏tftp-no-blocksize הוא הכפתור ההפוך.

# #141: מכונה לא רשומה לא מקבלת GRUB בכלל — dhcp-boot ב-imagectl-dhcp.conf
# (נכתב מהקונסולה) דורש tag:known, וזה נדלק רק למי שברשימה הזו. הקובץ
# נכתב ונקרא-מחדש (SIGHUP, לא restart) על ידי השרת עצמו — server/dhcp_host.py.
dhcp-hostsfile=/etc/imagectl/known-macs
EOF
if [[ -n "$IFACE" ]]; then
    run systemctl enable dnsmasq
    if (( ! DRY_RUN )); then
        systemctl restart dnsmasq || {
            journalctl -u dnsmasq -n 20 --no-pager >&2 || true
            die "dnsmasq לא עלה. תקן ונסה שוב."
        }
    fi
else
    # ‏#1088: הקונסולה מפעילה (enable + restart) כשמודלק DHCP על כרטיס ההפצה.
    say "dnsmasq נשאר כבוי עד שתוגדר רשת ההפצה מהקונסולה"
    run systemctl disable --now dnsmasq
fi

# ---------------------------------------------------------------------------
# חומת אש nftables לפי וילן (#1074 / R20-F1)
# ---------------------------------------------------------------------------
#
# נכתבת כאן, בהתקנה, לא בשדרוג: tools/server-upgrade.sh אינו מפעיל
# nftables — שרת קיים לא ינותק. --no-firewall מדלג עם אזהרה ביומן.

if (( NO_FIREWALL )); then
    warn "ללא חומת אש — R20-F1"
else
    say "מתקין ומפעיל חומת אש nftables (הפצה=${IFACE:-טרם הוגדר}, שרתים=$SERVERS_IF)"
    run env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq nftables
    NFT_GEN="$APP_DIR/install/nftables-rules.sh"
    [[ -f "$NFT_GEN" ]] || NFT_GEN="$SCRIPT_DIR/nftables-rules.sh"
    [[ -f "$NFT_GEN" ]] || die "חסר מחולל חומת האש: install/nftables-rules.sh"
    # ‏#1088: בלי כרטיס הפצה המחולל כותב רק את כללי וילן השרתים; הקונסולה
    # מריצה אותו שוב עם --deploy-if כשמודלק DHCP (server/deploy_net.py).
    NFT_ARGS=(--servers-if "$SERVERS_IF")
    [[ -n "$IFACE" ]] && NFT_ARGS+=(--deploy-if "$IFACE")
    if [[ "$STORAGE_ROLE" == "secondary" ]]; then
        PRIMARY_IP="${PRIMARY_URL#http://}"
        PRIMARY_IP="${PRIMARY_IP#https://}"
        PRIMARY_IP="${PRIMARY_IP%%/*}"
        PRIMARY_IP="${PRIMARY_IP%%:*}"
        [[ -n "$PRIMARY_IP" ]] || die "שרת משני: לא הצלחתי לגזור כתובת מ-$PRIMARY_URL"
        # ‏#1088: כתובת הראשי יכולה להיות שם (pairing לפי FQDN). חומת האש
        # מצמידה כתובת, לא שם — פותרים עכשיו ואומרים זאת: ראשי שמקבל DHCP
        # בלי reservation יחליף כתובת והכלל יתיישן.
        if [[ ! "$PRIMARY_IP" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            RESOLVED="$(getent ahostsv4 "$PRIMARY_IP" 2>/dev/null | awk 'NR==1 {print $1}')"
            [[ -n "$RESOLVED" ]] || die "שרת משני: השם $PRIMARY_IP לא נפתר לכתובת — חומת האש צריכה כתובת"
            warn "חומת האש תפתח 8443 ל-$RESOLVED (מה ש-$PRIMARY_IP פותר אליו עכשיו); אם הראשי בלקוח DHCP — קבעו לו reservation"
            PRIMARY_IP="$RESOLVED"
        fi
        NFT_ARGS+=(--primary-ip "$PRIMARY_IP")
    fi
    if (( DRY_RUN )); then
        printf '%s    would run: sh %s %s | nft -c -f -%s\n' \
            "$DIM" "$NFT_GEN" "${NFT_ARGS[*]}" "$OFF"
        printf '%s    would install /etc/nftables.conf and enable nftables%s\n' \
            "$DIM" "$OFF"
    else
        tmp="$(mktemp)"
        sh "$NFT_GEN" "${NFT_ARGS[@]}" > "$tmp" \
            || { rm -f "$tmp"; die "מחולל חומת האש נכשל"; }
        nft -c -f "$tmp" || {
            cat "$tmp" >&2 || true
            rm -f "$tmp"
            die "תחביר חומת האש אינו תקין (nft -c). המתקין עוצר."
        }
        install -m 0644 "$tmp" /etc/nftables.conf
        rm -f "$tmp"
        systemctl enable --now nftables || {
            journalctl -u nftables -n 20 --no-pager >&2 || true
            die "nftables לא עלה. תקן ונסה שוב, או --no-firewall."
        }
    fi
fi

# מצב proxy רץ באינסטנס dnsmasq נפרד ‏(#36): ‏dnsmasq 2.91 קופא על בקשת
# PXE לפורט 4011 במצב proxy, ובאינסטנס משותף הקפיאה הזו מורידה גם את
# ה-DHCP של וילן ההפצה. התיקייה והיחידה מותקנות כאן; הקובץ עצמו נכתב
# מהקונסולה, והיחידה נשארת כבויה עד שמדליקים proxy על כרטיס.
say "מכין את אינסטנס ה-proxy המבודד (כבוי עד שיודלק מהקונסולה)"
run install -d -m 0755 /etc/imagectl
run install -m 0644 "$APP_DIR/install/imagectl-proxy.service" \
    /etc/systemd/system/imagectl-proxy.service

# ---------------------------------------------------------------------------
# השרת והקונסולה: משתמש המנהל, יחידת systemd, והרמה
# ---------------------------------------------------------------------------

say "יוצר את משתמש המנהל ומרים את השרת"
run install -d "$DATA_DIR"
if (( ! DRY_RUN )); then
    ADMIN_USER="$ADMIN_USER" ADMIN_PASS="$ADMIN_PASS" \
    python3 - <<PYEOF
import os, sys, sqlite3
sys.path.insert(0, "$APP_DIR")
from server.db import connect
from server import users
conn = connect("$DATA_DIR/imagectl.db")
username = os.environ["ADMIN_USER"]
password = os.environ.get("ADMIN_PASS") or ""
if password:
    try:
        users.create(conn, username, password, "admin", by="installer",
                     is_builtin=True, must_change_password=False,
                     check_policy=False)
    except (sqlite3.IntegrityError, users.UsernameTaken):
        # שם תפוס בלבד. כל כשל אחר — דיסק, נעילה — עולה החוצה (#504).
        users.update(conn, username, by="installer",
                     password=password, role="admin", check_policy=False)
else:
    users.ensure_admin(conn)
row = conn.execute(
    "SELECT role FROM users WHERE username = ? COLLATE NOCASE", (username,)
).fetchone()
if password and (row is None or row["role"] != "admin"):
    sys.exit("המתקין לא הבטיח מנהל: %s הוא %s" % (
        username, "חסר" if row is None else row["role"]))
if not password:
    row = conn.execute(
        "SELECT role FROM users WHERE role = 'admin' LIMIT 1"
    ).fetchone()
    if row is None:
        sys.exit("המתקין לא הבטיח מנהל")
PYEOF
fi

# ---------------------------------------------------------------------------
# ‏#1088: כרטיס השרתים — לקוח DHCP (ברירת מחדל) או סטטי, בקובץ שהקונסולה
# יודעת לקרוא ולשנות (`interfaces.d/imagectl-<if>`, server/netcfg.py),
# ובהגדרה ב-DB שהקונסולה מציגה ("לקוח DHCP"/"כתובת סטטית"). ההגדרה של
# מתקין דביאן באותו כרטיס ב-/etc/network/interfaces עוברת להערה (עם
# גיבוי) — שתי הגדרות לאותו כרטיס הן שני ifup. **אין ifup כאן**: המתקין
# עצמו מחובר דרך הכרטיס הזה; ההגדרה נכנסת באתחול הבא (או מהקונסולה).
# ---------------------------------------------------------------------------

say "כותב את הגדרת כרטיס השרתים $SERVERS_IF ($SERVERS_MODE)"
if (( ! DRY_RUN )); then
    SERVERS_IF="$SERVERS_IF" SERVERS_MODE="$SERVERS_MODE" SERVERS_ADDR="$SERVERS_ADDR" \
    SERVERS_MASK="$SERVERS_MASK" SERVERS_GW="$SERVERS_GW" SERVERS_DNS="$SERVERS_DNS" \
    python3 - <<NETEOF
import os, socket, sys
sys.path.insert(0, "$APP_DIR")
from server import netcfg, netcfg_host
from server.db import connect, set_setting
cfg = netcfg.NetConfig(
    name=os.environ["SERVERS_IF"], mode=os.environ["SERVERS_MODE"],
    address=os.environ["SERVERS_ADDR"], netmask=os.environ["SERVERS_MASK"] or "255.255.255.0",
    gateway=os.environ["SERVERS_GW"],
    dns=[d.strip() for d in os.environ["SERVERS_DNS"].split(",") if d.strip()])
problems = netcfg.problems(cfg, [cfg])
if problems:
    sys.exit("הגדרת כרטיס השרתים אינה תקינה: " + " · ".join(problems))
notes, error = netcfg_host.adopt_interface(
    cfg.name, netcfg.render(cfg, hostname=socket.gethostname()))
for note in notes:
    print("    " + note)
if error:
    sys.exit(error)
conn = connect("$DATA_DIR/imagectl.db")
set_setting(conn, netcfg.SETTING_PREFIX + cfg.name, cfg.to_json())
NETEOF
fi

run install -m 0644 "$APP_DIR/install/imagectl-server.service" \
    /etc/systemd/system/imagectl-server.service

# ההחזרה האוטומטית של שינוי רשת שלא אושר ‏(#56). מותקנת ומופעלת כאן, ולא
# "כשיצטרכו": בלי הטיימר הזה הקונסולה **חוסמת** כל שינוי כתובת שיכול
# לנתק אותה, ומפעיל שפוגש חסימה בלי להבין למה ילך לערוך קבצים ב-SSH —
# כלומר בדיוק לאותה עבודה שהלשונית הזאת נועדה להחליף. שים לב
# ש-`--state-dir` ביחידה חייב להיות $DATA_DIR/netcfg.
run install -m 0644 "$APP_DIR/install/imagectl-netrollback.service" \
    /etc/systemd/system/imagectl-netrollback.service
run install -m 0644 "$APP_DIR/install/imagectl-netrollback.timer" \
    /etc/systemd/system/imagectl-netrollback.timer
run install -d -m 0755 "$DATA_DIR/netcfg"
# תצורת ה-Storage Node שעוברת ל-server.main דרך היחידה, וגם
# `--boot-dir` מ-`--http-root` (#395): בלי זה המתקין כותב לתיקייה
# שהשרת אינו מגיש. ‏ExecStart משתמש ב-$IMAGECTL_STORAGE_ARGS (בלי
# סוגריים) — systemd מפצל אותו למילים.
if [[ "$STORAGE_ROLE" == "secondary" ]]; then
    STORAGE_ARGS="--storage-role secondary --primary-url $PRIMARY_URL --boot-dir $HTTP_ROOT"
else
    STORAGE_ARGS="--storage-role standalone --boot-dir $HTTP_ROOT"
fi
# ‏#1088: ‏--interface רק כשיש כרטיס הפצה; בלעדיו השרת קורא את הכרטיס
# והכתובת ממה שהקונסולה רושמת (deploy:interface/deploy:url), ו-IMAGECTL_URL
# נשאר ריק — היחידה מעבירה ${IMAGECTL_URL} כארגומנט ריק, וזה מה שאומר
# ל-server.main "מהקונסולה".
if [[ -n "$IFACE" ]]; then
    STORAGE_ARGS+=" --interface $IFACE"
fi
if [[ "$TFTP_ROOT" != "/srv/tftp" ]]; then
    STORAGE_ARGS+=" --tftp-root $TFTP_ROOT"
fi
# ‏#703 (tracer 5) / #1088: הקונסולה על כרטיס הניהול — ברירת המחדל היא
# כרטיס השרתים **לפי שם**, כדי שהיא תעקוב אחרי הכתובת שה-DHCP נותן.
# מצורף לאותו משתנה שהיחידה מרחיבה.
if [[ -n "$CONSOLE_HOST" ]]; then
    STORAGE_ARGS+=" --console-host $CONSOLE_HOST"
fi
write_file /etc/systemd/system/imagectl-server.service.d/override.conf <<EOF
# ImageCtl — נכתב על ידי המתקין: הכתובת שנגזרה מהכרטיס שנבחר
# (ריק = רשת ההפצה תוגדר מהקונסולה, #1088).
[Service]
Environment=IMAGECTL_URL=$SERVER_URL
# ‏בגרשיים: הערך מכיל רווחים (--storage-role X --primary-url Y), ובלי
# גרשיים systemd מפצל את שורת ה-Environment למילים וקולט רק
# IMAGECTL_STORAGE_ARGS=--storage-role → השרת קורס "expected one argument".
# ‏ExecStart מרחיב $IMAGECTL_STORAGE_ARGS בלי גרשיים כדי לפצל שוב לארגומנטים.
Environment="IMAGECTL_STORAGE_ARGS=$STORAGE_ARGS"
EOF
# ‏#703 (tracer 5): תעודת ה-TLS של הקונסולה נוצרת (או נטענת — התקנה
# חוזרת אינה מחליפה תעודה שהדפדפן כבר אישר) **לפני** שהשרת עולה, כדי
# שטביעת האצבע תודפס כאן ותושווה למה שהדפדפן מציג בכניסה הראשונה.
# השרת עצמו היה יוצר אותה בהפעלה הראשונה; כאן היא נוצרת במקום שהמפעיל
# רואה. ‏SAN = כרטיס הניהול (או 127.0.0.1) + שם המארח.
say "מייצר/מוודא את תעודת ה-TLS של הקונסולה"
# ‏#1088: כש---console-host הוא שם כרטיס, ה-SAN הוא הכתובת **הנוכחית** שלו
# (+ שם המארח, שנוסף ממילא); בלי כתובת עדיין — loopback, והתעודה תקפה
# לפי השם. שם כרטיס אינו נכנס כ-SAN: הדפדפן לעולם לא יפנה ל-"eth0".
CONSOLE_TLS_HOST="$CONSOLE_HOST"
if [[ -n "$CONSOLE_TLS_HOST" && ! "$CONSOLE_TLS_HOST" =~ ^[0-9a-fA-F.:]+$ ]]; then
    CONSOLE_TLS_HOST="$(iface_ip "$CONSOLE_TLS_HOST")"
fi
CONSOLE_FP="(dry-run)"
if (( ! DRY_RUN )); then
    CONSOLE_FP="$(CONSOLE_HOST="${CONSOLE_TLS_HOST:-127.0.0.1}" python3 - <<TLSEOF
import os, sys
sys.path.insert(0, "$APP_DIR")
from server.console_tls import ensure_console_cert
tls = ensure_console_cert("$DATA_DIR", os.environ["CONSOLE_HOST"])
print(tls.fingerprint_sha256)
TLSEOF
)" || die "יצירת תעודת הקונסולה נכשלה"
    if [[ ! "$CONSOLE_FP" =~ ^([0-9A-F]{2}:){31}[0-9A-F]{2}$ ]]; then
        die "טביעת האצבע של תעודת הקונסולה אינה בצורה הצפויה: $CONSOLE_FP"
    fi
fi
run systemctl daemon-reload
run systemctl enable --now imagectl-netrollback.timer
run systemctl enable --now imagectl-server

# ---------------------------------------------------------------------------
# סיכום
# ---------------------------------------------------------------------------

# ‏#1088: הכתובת שמדפיסים היא זו של כרטיס השרתים **עכשיו**; בלקוח DHCP
# היא יכולה להתחלף — ואז השם (hostname ב-DNS של המכללה) הוא הדרך היציבה.
CONSOLE_SHOWN="${CONSOLE_TLS_HOST:-127.0.0.1}"
cat <<EOF

  קונסולה        https://${CONSOLE_SHOWN}:8081  (משתמש: $ADMIN_USER)
                 גם https://$(hostname):8081 — כרטיס השרתים $SERVERS_IF ב-$SERVERS_MODE;
                 בלקוח DHCP הכתובת יכולה להתחלף, הקונסולה עוקבת אחריה (#1088)
                 כניסה ראשונה: admin / admin — הקונסולה תדרוש החלפת סיסמה
                 תעודה עצמית — הדפדפן יבקש אישור פעם אחת; להשוות:
                 SHA-256 $CONSOLE_FP
  רשת הפצה       ${IFACE:+$IFACE · $SERVER_URL}${IFACE:-לא הוגדרה — דף הרשת בקונסולה: בחר כרטיס → כתובת → DHCP}
  TFTP root      $TFTP_ROOT  (bootx64.efi -> grubx64.efi -> grub/grub.cfg)
  נתונים         $DATA_DIR · אימג'ים: $IMAGES_DIR
EOF

# ---------------------------------------------------------------------------
# שער הסיום — "מוכן." רק כשתחנה באמת יכולה לעלות (#332)
# ---------------------------------------------------------------------------
#
# ההתקנה יצאה 0 והדפיסה "מוכן." בזמן ש-$HTTP_ROOT הייתה ריקה ושני
# הקבצים שהתפריט מפנה אליהם החזירו 404. זו הגרסה החמורה של עיקרון 5:
# לא בדיקה שנכשלה בשקט, אלא הצהרת הצלחה מפורשת על מצב שאינו עובד.
#
# השער נכון בשתי התשובות להכרעה שעדיין פתוחה — האם המתקין יבנה את
# ה-initrd ויעתיק את הקרנל בעצמו. אם יבנה, השער יתפוס בנייה שנכשלה;
# ואם לא, הוא לא ייפרד מהמפעיל במילה "מוכן".

READY=1
# ‏#1088: בלי כרטיס הפצה הסוכן מאזין על loopback בלבד — הבדיקה שואלת אותו שם.
# (אחרי READY=1: tests/test_boot_payload_gate.py מריץ את הקטע מכאן ועד הסוף.)
VERIFY_URL="${SERVER_URL:-http://127.0.0.1:${PORT:-8080}}"
if (( DRY_RUN )); then
    printf '%s    would run: install/verify-boot-payload.sh --server-url %s%s\n' \
        "$DIM" "$VERIFY_URL" "$OFF"
else
    say "בודק שהשרת מגיש את הקרנל ואת ה-initrd"
    bash "$APP_DIR/install/verify-boot-payload.sh" \
        --app-dir "$APP_DIR" --http-root "$HTTP_ROOT" --server-url "$VERIFY_URL" \
        || READY=0
fi

# הבדיקה כבר אמרה מה חסר ומה עושים. "מוכן." לא נאמר כאן.
(( READY )) || exit 1

cat <<EOF

$(printf '%s' "$GRN")מוכן.$(printf '%s' "$OFF")

$(printf '%s' "$YEL")מה עושים עכשיו — הכל מהקונסולה:$(printf '%s' "$OFF")

  1. דף הרשת: ${IFACE:+מדליקים DHCP או proxy על הכרטיס — עם כל שכבות הבטיחות.}${IFACE:-בוחרים את כרטיס ההפצה, קובעים לו כתובת סטטית (עריכת כתובת),
     ואז מדליקים עליו DHCP — ההדלקה משלימה את ההתקנה (grub.cfg, dnsmasq,
     חומת אש) ומאתחלת את השרת על כתובת ההפצה (#1088).}
  2. מסך הבריאות: רמזור לכל בדיקה — פורטים, dnsmasq, TFTP, השרת.
  3. מסך המחשבים: טבלאות ה-MAC.

EOF
