#!/usr/bin/env bash
#
# ImageCtl — התקנה מלאה על שרת דביאן: שרשרת האתחול, השרת והקונסולה.
#
# הרצה אחת, ארבע שאלות, וזהו:
#   1. איזה כרטיס רשת (מרשימה של מה שקיים)
#   2. שם משתמש למנהל
#   3. סיסמה
#   4. אישור סיסמה
#
#   sudo ./setup-boot-server.sh
#
# כל השאר בקונסולה: DHCP לכל כרטיס (לשונית הרשת, אפיון סעיף 24),
# בדיקות מצב (מסך הבריאות). הטרמינל נוגעים בו פעם אחת — כאן.
#
# ראו docs/server-install.md להסבר מלא.

set -euo pipefail

# ---------------------------------------------------------------------------
# ברירות מחדל (הדגלים כולם רשות — לאוטומציה ולדיבאג, לא לזרימה הרגילה)
# ---------------------------------------------------------------------------

SERVER_URL=""
IFACE=""
ADMIN_USER=""
ADMIN_PASS=""
TFTP_ROOT="/srv/tftp"
HTTP_ROOT="/srv/imagectl/boot"
APP_DIR="/opt/imagectl"
DATA_DIR="/var/lib/imagectl"
IMAGES_DIR="/srv/imagectl/images"
# הריפו שונה שמו ל-ImageCtl-archive ב-09/2026 והפך לפרטי; השם הישן
# `NadavOked/ImageCtl` שייך היום לפרויקט אחר, ו-clone ממנו היה מתקין
# קוד זר על שרת האתחול בלי להתלונן. ‏clone מהארכיון דורש אישורים
# ונכשל בקול — וזה המצב הרצוי מבין השניים.
REPO_URL="https://github.com/NadavOked/ImageCtl-archive"
DRY_RUN=0
PORT=8080

# ---------------------------------------------------------------------------
# הקובץ הקבוע ל-GRUB
# ---------------------------------------------------------------------------
#
# מוטמע כאן כדי שהסקריפט יעבוד גם בלי הריפו. המקור האמיתי הוא
# boot/grub_menu.py:render_bootstrap(); הטסט
# tests/test_installer_matches_generator.py משווה בין השניים.

read -r -d '' GRUB_BOOTSTRAP <<'GRUBCFG' || true
# ImageCtl bootstrap - generated by boot/grub_menu.py:render_bootstrap().
# Lives on the TFTP root as grub/grub.cfg. Regenerate, do not hand-edit.

set pager=0
set timeout=0
set timeout_style=hidden

# efinet exists only on UEFI; the i386-pc netboot core (the cloning
# machines, #38) has its driver built in, and insmod-ing a module that
# does not exist prints an error on the boot screen.
if [ "$grub_platform" = "efi" ]; then insmod efinet; fi
insmod http
insmod tftp

function try_chain {
    unset espdev
    search --no-floppy --file --set=espdev "$1"
    if [ -n "$espdev" ]; then
        set root=$espdev
        if chainloader "$1"; then
            boot
        else
            if [ -z "$chain_refused" ]; then set chain_refused=$1; fi
        fi
    fi
}

function chain_local {
    insmod part_gpt
    insmod fat
    insmod chain
    insmod search_fs_file
    unset chain_refused

    for path in /EFI/Microsoft/Boot/bootmgfw.efi /EFI/ubuntu/shimx64.efi /EFI/ubuntu/grubx64.efi /EFI/debian/shimx64.efi /EFI/debian/grubx64.efi /EFI/fedora/shimx64.efi /EFI/fedora/grubx64.efi /EFI/centos/shimx64.efi /EFI/rocky/shimx64.efi /EFI/almalinux/shimx64.efi /EFI/opensuse/shim.efi /EFI/BOOT/bootx64.efi; do
        try_chain "$path"
    done

    echo ""
    if [ -n "$chain_refused" ]; then
        echo "A boot loader WAS found on the local disk:"
        echo "  $chain_refused"
        echo "but this menu was refused permission to start it (see the error above)."
        if [ "$shim_lock" = "y" ]; then
            echo "Why: Secure Boot is on. Every chainload from this menu is checked"
            echo "by shim, and shim did not accept this file's signature."
            echo "The disk and the operating system are most likely intact."
            echo "To start it now: power off, then boot from the disk directly"
            echo "(firmware boot menu, usually F12), bypassing PXE."
        else
            echo "Why: unknown. GRUB does not report a shim lock, so this is"
            echo "not a Secure Boot refusal. Read the error above."
        fi
    else
        echo "No operating system found on the local disk."
    fi
    echo "Contact IT. This computer will stay powered on."
    set stay_on=y
    while [ "$stay_on" = "y" ]; do
        sleep --interruptible 60
    done
}

function try_local {
    if [ "$grub_platform" = "efi" ]; then
        echo "Booting from the local disk."
        chain_local
    fi

    echo ""
    echo "This machine booted in Legacy BIOS mode, which on this network"
    echo "means a cloning machine. It has no local system to start, and the"
    echo "drives attached to it are the payload - they are never booted from."
    echo "Nothing will be started."
    echo "Fix the server or the network, then power-cycle this machine."
    echo "Contact IT. This computer will stay powered on."
    set stay_on=y
    while [ "$stay_on" = "y" ]; do
        sleep --interruptible 60
    done
}

# GRUB fills net_default_mac from the interface that PXE-booted, already in
# lowercase-with-colons form -- the canonical format from the interface spec.
if [ -z "$net_default_mac" ]; then
    echo "ImageCtl: no network interface reported."
    sleep --interruptible 3
    try_local
fi

# Deployment address. net_default_server -- the DHCP or PXE-proxy server that
# actually answered this station -- comes first, because it is the only address
# that is right on every network: a station booted by a proxy on a foreign VLAN
# (spec scenario 3) often cannot reach the deployment VLAN address at all. The
# port is not in DHCP, so it comes from the configured address.
# The explicit address stays as a fallback, for debugging and for the case
# where next-server arrives empty or points at a machine without ImageCtl.
set imagectl_fallback=@@GRUB_HOST@@
if [ -n "$net_default_server" ]; then
    set imagectl_server=${net_default_server}:@@GRUB_PORT@@
else
    set imagectl_server=$imagectl_fallback
fi

# Three attempts: GRUB's EFI http stack sometimes fails its very first
# connection on a cold boot while TFTP already works (#31). A retry a
# second later succeeds; only a server that is really down falls through.
# Each attempt also tries the fallback, unless it is the same address.
for attempt in 1 2 3; do
    configfile (http,$imagectl_server)/boot/menu?mac=$net_default_mac
    if [ "$imagectl_server" != "$imagectl_fallback" ]; then
        configfile (http,$imagectl_fallback)/boot/menu?mac=$net_default_mac
    fi
    sleep 1
done

# Reached only if every fetch failed -- server down, cable out, DHCP wrong.
# try_local, not chain_local: this file runs before the machine has asked
# about its own MAC, so it cannot know it is a cloning machine -- and with
# the server down there is nobody to ask. $grub_platform is the one thing
# it does know (#323).
echo "ImageCtl: server $imagectl_server unreachable."
sleep --interruptible 3
try_local
GRUBCFG

# ---------------------------------------------------------------------------
# עזרים
# ---------------------------------------------------------------------------

RED=$'\033[31m'; YEL=$'\033[33m'; GRN=$'\033[32m'; DIM=$'\033[2m'; OFF=$'\033[0m'

say()  { printf '%s==>%s %s\n' "$GRN" "$OFF" "$*"; }
warn() { printf '%s[!]%s %s\n' "$YEL" "$OFF" "$*" >&2; }
die()  { printf '%s[x]%s %s\n' "$RED" "$OFF" "$*" >&2; exit 1; }

run() {
    if (( DRY_RUN )); then
        printf '%s    would run: %s%s\n' "$DIM" "$*" "$OFF"
    else
        "$@"
    fi
}

write_file() {
    # write_file <path> <<'EOF' ... EOF
    local path="$1" content
    content="$(cat)"
    if (( DRY_RUN )); then
        printf '%s    would write %s (%d bytes)%s\n' "$DIM" "$path" "${#content}" "$OFF"
        return
    fi
    install -d "$(dirname "$path")"
    if [[ -f "$path" ]] && ! grep -q "ImageCtl" "$path" 2>/dev/null; then
        # קובץ שלא אנחנו כתבנו — מגבים במקום לדרוס.
        cp -a "$path" "${path}.pre-imagectl.$(date +%Y%m%d%H%M%S)"
        warn "backed up existing $path"
    fi
    printf '%s\n' "$content" > "$path"
}

usage() {
    cat <<'EOF'
ImageCtl — התקנה מלאה על שרת דביאן: שרשרת אתחול, שרת וקונסולה.

  sudo ./setup-boot-server.sh

ההתקנה שואלת ארבע שאלות (כרטיס רשת, משתמש מנהל, סיסמה ואישורה)
ומרימה הכל. DHCP לא נדלק כאן בכלל — מגדירים אותו אחר כך מהקונסולה,
לשונית הרשת, עם כל שכבות הבטיחות (אפיון סעיף 24).

דגלים (רשות — לאוטומציה ולדיבאג בלבד):
  --interface IFACE    מדלג על שאלת הכרטיס
  --server-url URL     עוקף את הכתובת הנגזרת מהכרטיס (http בלבד)
  --admin-user NAME    מדלג על שאלת המשתמש
  --admin-pass PASS    מדלג על שאלות הסיסמה (נשאר בהיסטוריית השלל — לדיבאג)
  --tftp-root PATH     ברירת מחדל /srv/tftp
  --http-root PATH     ברירת מחדל /srv/imagectl/boot
  --dry-run            מראה מה יקרה בלי לשנות כלום
  -h, --help           המסך הזה
EOF
}

# ---------------------------------------------------------------------------
# פירוק ארגומנטים
# ---------------------------------------------------------------------------

while [[ $# -gt 0 ]]; do
    case "$1" in
        --interface)   IFACE="${2:?}"; shift 2 ;;
        --server-url)  SERVER_URL="${2:?}"; shift 2 ;;
        --admin-user)  ADMIN_USER="${2:?}"; shift 2 ;;
        --admin-pass)  ADMIN_PASS="${2:?}"; shift 2 ;;
        --tftp-root)   TFTP_ROOT="${2:?}"; shift 2 ;;
        --http-root)   HTTP_ROOT="${2:?}"; shift 2 ;;
        --dry-run)     DRY_RUN=1; shift ;;
        -h|--help)     usage; exit 0 ;;
        --mode|--dhcp-range)
            die "הדגל $1 בוטל: DHCP מוגדר מהקונסולה, לשונית הרשת (אפיון סעיף 24)." ;;
        *)             die "unknown option: $1  (try --help)" ;;
    esac
done

(( DRY_RUN )) || [[ $EUID -eq 0 ]] || die "צריך להריץ עם sudo (או --dry-run כדי רק לראות)."

# ---------------------------------------------------------------------------
# שאלה 1 — כרטיס הרשת, מתוך רשימה של מה שקיים
# ---------------------------------------------------------------------------

iface_ip() { ip -4 -o addr show dev "$1" 2>/dev/null | awk '{print $4}' | cut -d/ -f1 | head -n1; }

if [[ -z "$IFACE" ]]; then
    mapfile -t NICS < <(ip -br link | awk '$1 != "lo" {print $1}' | cut -d@ -f1)
    (( ${#NICS[@]} )) || die "לא נמצאו כרטיסי רשת."
    say "כרטיסי הרשת במכונה:"
    for i in "${!NICS[@]}"; do
        n="${NICS[$i]}"
        state="$(cat "/sys/class/net/$n/operstate" 2>/dev/null || echo '?')"
        printf '  %d) %-12s %-6s %s\n' "$((i + 1))" "$n" "$state" "$(iface_ip "$n")"
    done
    read -r -p "על איזה כרטיס יאזין השרת? [1]: " pick
    pick="${pick:-1}"
    [[ "$pick" =~ ^[0-9]+$ ]] && (( pick >= 1 && pick <= ${#NICS[@]} )) \
        || die "אין כרטיס מספר $pick ברשימה."
    IFACE="${NICS[$((pick - 1))]}"
fi
ip link show "$IFACE" >/dev/null 2>&1 || die "לא קיים ממשק בשם $IFACE"

# הכתובת נגזרת מהכרטיס — אין סיבה להקליד אותה.
if [[ -z "$SERVER_URL" ]]; then
    ADDR="$(iface_ip "$IFACE")"
    [[ -n "$ADDR" ]] || die "לכרטיס $IFACE אין כתובת IP.
    קבעו לו כתובת סטטית (זה שרת) והריצו שוב."
    SERVER_URL="http://$ADDR:$PORT"
fi
case "$SERVER_URL" in
    http://*)  ;;
    https://*) die "https לא נתמך: ה-GRUB החתום של דביאן נבנה בלי TLS. השתמש ב-http." ;;
    *)         die "--server-url חייב להתחיל ב-http:// (התקבל: $SERVER_URL)" ;;
esac
GRUB_HOST="${SERVER_URL#http://}"; GRUB_HOST="${GRUB_HOST%%/*}"
# הפורט לבדו — קובץ ה-GRUB מרכיב איתו את הכתובת שה-DHCP/proxy ענה בפועל.
# ‏if מלא ולא "&&": תחת set -e תנאי שנכשל בשורה עליונה מפיל את הסקריפט.
GRUB_PORT="${GRUB_HOST##*:}"
if [[ "$GRUB_PORT" == "$GRUB_HOST" ]]; then GRUB_PORT=80; fi

# ---------------------------------------------------------------------------
# שאלות 2–4 — משתמש המנהל
# ---------------------------------------------------------------------------

if [[ -z "$ADMIN_USER" ]]; then
    read -r -p "שם משתמש למנהל [admin]: " ADMIN_USER
    ADMIN_USER="${ADMIN_USER:-admin}"
fi
while [[ -z "$ADMIN_PASS" ]]; do
    read -r -s -p "סיסמה (8 תווים לפחות): " p1; echo
    read -r -s -p "אישור סיסמה: " p2; echo
    if (( ${#p1} < 8 )); then warn "קצרה מדי — 8 תווים לפחות."
    elif [[ "$p1" != "$p2" ]]; then warn "הסיסמאות אינן זהות. שוב."
    else ADMIN_PASS="$p1"; fi
done

say "כרטיס: $IFACE · כתובת: $SERVER_URL · מנהל: $ADMIN_USER"

# ---------------------------------------------------------------------------
# חבילות וקוד
# ---------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PKGS=(shim-signed grub-efi-amd64-signed grub-pc-bin dnsmasq
      python3-fastapi python3-uvicorn)
[[ -f "$SCRIPT_DIR/../server/main.py" ]] || PKGS+=(git)

say "מתקין חבילות: ${PKGS[*]}"
run env DEBIAN_FRONTEND=noninteractive apt-get update -qq
run env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq "${PKGS[@]}"

if [[ -f "$SCRIPT_DIR/../server/main.py" ]]; then
    SRC="$(cd "$SCRIPT_DIR/.." && pwd)"
    if [[ "$SRC" != "$APP_DIR" ]]; then
        say "מעתיק את הקוד אל $APP_DIR"
        run install -d "$APP_DIR"
        run cp -a "$SRC/." "$APP_DIR/"
    fi
else
    # ‏git נכשל כאן בקול, אבל בהודעה **שלו**: "could not read Username for
    # 'https://github.com'". למי שמתקין שרת ואינו מכיר את הריפו זו הודעה
    # שאינה אומרת לא מה קרה ולא מה לעשות — ‏ImageCtl-archive הוא ריפו
    # פרטי, ו-clone אנונימי ממנו לא יצליח לעולם. אותו דפוס כמו
    # ‏`Unable to locate package` של fonts-ibm-plex (#120): כשל אמיתי,
    # הודעה שמובילה לכיוון הלא נכון.
    say "מושך את הקוד מ-$REPO_URL"
    if [[ -d "$APP_DIR/.git" ]]; then
        run git -C "$APP_DIR" pull --ff-only || die "\
עדכון הקוד ב-$APP_DIR נכשל (git pull). ראה את שגיאת git למעלה."
    else
        run git clone --depth 1 "$REPO_URL" "$APP_DIR" || die "\
‏git clone מ-$REPO_URL נכשל.

‏ImageCtl-archive הוא ריפו **פרטי**: ‏clone בלי אישורים נכשל תמיד, וזו
הסיבה הסבירה ביותר לשגיאת git שמופיעה למעלה.

הדרך המומלצת — להביא את הריפו אל השרת ולהריץ את המתקין מתוכו:

  (מתחנה שיש לה גישה לריפו)
  git clone https://github.com/NadavOked/ImageCtl-archive imagectl
  tar czf imagectl.tgz imagectl && scp imagectl.tgz <שרת>:/tmp/

  (על השרת)
  tar xzf /tmp/imagectl.tgz -C ~ && cd ~/imagectl
  sudo bash install/setup-boot-server.sh

כשהריפו נמצא לצד הסקריפט המתקין מעתיק ממנו ואינו פונה לרשת כלל.
לחלופין: הגדר אישורי git על השרת (credential helper או SSH) והרץ שוב."
    fi
fi

# ---------------------------------------------------------------------------
# שרשרת האתחול: shim ו-GRUB חתומים + הקובץ הקבוע
# ---------------------------------------------------------------------------
#
# שני הקבצים חייבים להיות אלה של דביאן — shim חתום מיקרוסופט ו-GRUB
# חתום דביאן. shim מחפש את grubx64.efi בשם הזה בדיוק, באותה תיקייה.

SHIM_SRC="/usr/lib/shim/shimx64.efi.signed"
GRUB_SRC="/usr/lib/grub/x86_64-efi-signed/grubnetx64.efi.signed"

say "מעתיק shim ו-GRUB חתומים אל $TFTP_ROOT"
for src in "$SHIM_SRC" "$GRUB_SRC"; do
    [[ -f "$src" ]] || (( DRY_RUN )) || die "לא נמצא: $src — בדוק: dpkg -L shim-signed | grep efi"
done
run install -d -m 0755 "$TFTP_ROOT" "$TFTP_ROOT/grub" "$HTTP_ROOT" "$IMAGES_DIR"
run install -m 0644 "$SHIM_SRC" "$TFTP_ROOT/bootx64.efi"
run install -m 0644 "$GRUB_SRC" "$TFTP_ROOT/grubx64.efi"

# מחשבי השיכפול הם Legacy BIOS (#38) — GRUB i386-pc לרשת, מאותו עץ
# grub/ ועם אותו grub.cfg בדיוק. ה-DHCP בוחר טוען לפי אופציה 93.
say "בונה GRUB i386-pc למחשבי ה-Legacy (grub-mknetdir)"
run grub-mknetdir --net-directory="$TFTP_ROOT" --subdir=grub

say "כותב את grub/grub.cfg עבור $GRUB_HOST"
CFG_TEXT="${GRUB_BOOTSTRAP//@@GRUB_HOST@@/$GRUB_HOST}"
CFG_TEXT="${CFG_TEXT//@@GRUB_PORT@@/$GRUB_PORT}"
if (( DRY_RUN )); then
    printf '%s    would write %s/grub/grub.cfg%s\n' "$DIM" "$TFTP_ROOT" "$OFF"
else
    printf '%s\n' "$CFG_TEXT" > "$TFTP_ROOT/grub/grub.cfg"
    chmod 0644 "$TFTP_ROOT/grub/grub.cfg"
fi

# אין tftp-secure, בכוונה: הוא מגיש רק קבצים שבבעלות משתמש dnsmasq,
# ובשרת אתחול ייעודי שכל תוכנו ציבורי ממילא הוא לא מגן על כלום — רק
# מוסיף כשל שקט ("Permission denied") לכל קובץ חדש שנכתב כ-root.
# נכווינו פעמיים (#12, #38). ‏tftp-root תוחם את ההגשה לתיקייה הזו.

# ---------------------------------------------------------------------------
# dnsmasq — TFTP בלבד. DHCP לא נדלק בהתקנה: הוא מוגדר מהקונסולה,
# כרטיס-כרטיס, מאחורי שכבות הבטיחות של סעיף 24. הקונסולה כותבת
# ל-imagectl-dhcp.conf; הקובץ הזה נותן את הבסיס המשותף בלבד.
# ---------------------------------------------------------------------------

say "מגדיר dnsmasq (TFTP בלבד; DHCP יוגדר מהקונסולה)"
write_file /etc/dnsmasq.d/imagectl.conf <<EOF
# ImageCtl — נוצר על ידי install/setup-boot-server.sh. אל תערוך ביד.
# DHCP מוגדר מהקונסולה (לשונית הרשת) ונכתב ל-imagectl-dhcp.conf.
port=0

enable-tftp
tftp-root=$TFTP_ROOT
# אין צורך לקבוע גודל בלוק: ‏dnsmasq נענה אוטומטית ל-blksize שהלקוח
# מבקש (קושחות PXE מבקשות ~1468). ‏tftp-blocksize אינה אופציה קיימת —
# השירות מסרב לעלות איתה; ‏tftp-no-blocksize הוא הכפתור ההפוך.
EOF
run systemctl enable dnsmasq
if (( ! DRY_RUN )); then
    systemctl restart dnsmasq || {
        journalctl -u dnsmasq -n 20 --no-pager >&2 || true
        die "dnsmasq לא עלה. תקן ונסה שוב."
    }
fi

# מצב proxy רץ באינסטנס dnsmasq נפרד ‏(#36): ‏dnsmasq 2.91 קופא על בקשת
# PXE לפורט 4011 במצב proxy, ובאינסטנס משותף הקפיאה הזו מורידה גם את
# ה-DHCP של וילן ההפצה. התיקייה והיחידה מותקנות כאן; הקובץ עצמו נכתב
# מהקונסולה, והיחידה נשארת כבויה עד שמדליקים proxy על כרטיס.
say "מכין את אינסטנס ה-proxy המבודד (כבוי עד שיודלק מהקונסולה)"
run install -d -m 0755 /etc/imagectl
run install -m 0644 "$APP_DIR/install/imagectl-proxy.service" \
    /etc/systemd/system/imagectl-proxy.service

# ---------------------------------------------------------------------------
# השרת והקונסולה: משתמש המנהל, יחידת systemd, והרמה
# ---------------------------------------------------------------------------

say "יוצר את משתמש המנהל ומרים את השרת"
run install -d "$DATA_DIR"
if (( ! DRY_RUN )); then
    ADMIN_USER="$ADMIN_USER" ADMIN_PASS="$ADMIN_PASS" \
    python3 - <<PYEOF
import os, sys
sys.path.insert(0, "$APP_DIR")
from server.db import connect
from server import users
conn = connect("$DATA_DIR/imagectl.db")
try:
    users.create(conn, os.environ["ADMIN_USER"], os.environ["ADMIN_PASS"],
                 "admin", by="installer")
except Exception:
    users.update(conn, os.environ["ADMIN_USER"], by="installer",
                 password=os.environ["ADMIN_PASS"])
PYEOF
fi

run install -m 0644 "$APP_DIR/install/imagectl-server.service" \
    /etc/systemd/system/imagectl-server.service

# ההחזרה האוטומטית של שינוי רשת שלא אושר ‏(#56). מותקנת ומופעלת כאן, ולא
# "כשיצטרכו": בלי הטיימר הזה הקונסולה **חוסמת** כל שינוי כתובת שיכול
# לנתק אותה, ומפעיל שפוגש חסימה בלי להבין למה ילך לערוך קבצים ב-SSH —
# כלומר בדיוק לאותה עבודה שהלשונית הזאת נועדה להחליף. שים לב
# ש-`--state-dir` ביחידה חייב להיות $DATA_DIR/netcfg.
run install -m 0644 "$APP_DIR/install/imagectl-netrollback.service" \
    /etc/systemd/system/imagectl-netrollback.service
run install -m 0644 "$APP_DIR/install/imagectl-netrollback.timer" \
    /etc/systemd/system/imagectl-netrollback.timer
run install -d -m 0755 "$DATA_DIR/netcfg"
write_file /etc/systemd/system/imagectl-server.service.d/override.conf <<EOF
# ImageCtl — נכתב על ידי המתקין: הכתובת שנגזרה מהכרטיס שנבחר.
[Service]
Environment=IMAGECTL_URL=$SERVER_URL
EOF
run systemctl daemon-reload
run systemctl enable --now imagectl-netrollback.timer
run systemctl enable --now imagectl-server

# ---------------------------------------------------------------------------
# סיכום
# ---------------------------------------------------------------------------

cat <<EOF

$(printf '%s' "$GRN")מוכן.$(printf '%s' "$OFF")

  קונסולה        $SERVER_URL  (משתמש: $ADMIN_USER)
  TFTP root      $TFTP_ROOT  (bootx64.efi -> grubx64.efi -> grub/grub.cfg)
  נתונים         $DATA_DIR · אימג'ים: $IMAGES_DIR

$(printf '%s' "$YEL")מה עושים עכשיו — הכל מהקונסולה:$(printf '%s' "$OFF")

  1. לשונית הרשת: מדליקים DHCP או proxy על הכרטיס — עם כל שכבות הבטיחות.
  2. מסך הבריאות: רמזור לכל בדיקה — פורטים, dnsmasq, TFTP, השרת.
  3. מסך המחשבים: טבלאות ה-MAC.

EOF
